// SPDX-FileCopyrightText: 2026 henoSNES contributors
// SPDX-License-Identifier: GPL-3.0-or-later

// GENERADO por tools/gen_opcode_table/gen_opcode_table.py a partir de
// docs/refs/65c816-opcodes.md. No editar a mano.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace heno {

// 92 mnemónicos, en orden alfabético.
enum class Mnemonic : std::uint8_t {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRA,
    BRK,
    BRL,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    COP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JML,
    JMP,
    JSL,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    MVN,
    MVP,
    NOP,
    ORA,
    PEA,
    PEI,
    PER,
    PHA,
    PHB,
    PHD,
    PHK,
    PHP,
    PHX,
    PHY,
    PLA,
    PLB,
    PLD,
    PLP,
    PLX,
    PLY,
    REP,
    ROL,
    ROR,
    RTI,
    RTL,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    SEP,
    STA,
    STP,
    STX,
    STY,
    STZ,
    TAX,
    TAY,
    TCD,
    TCS,
    TDC,
    TRB,
    TSB,
    TSC,
    TSX,
    TXA,
    TXS,
    TXY,
    TYA,
    TYX,
    WAI,
    WDM,
    XBA,
    XCE,
};

// Modos de direccionamiento; el comentario indica el token de la tabla de referencia.
enum class AddrMode : std::uint8_t {
    Implied,                      // i
    Accumulator,                  // A
    Immediate,                    // #
    Absolute,                     // a
    AbsoluteX,                    // a,X
    AbsoluteY,                    // a,Y
    AbsoluteLong,                 // al
    AbsoluteLongX,                // al,X
    AbsoluteIndirect,             // (a)
    AbsoluteIndexedIndirect,      // (a,X)
    Direct,                       // d
    DirectX,                      // d,X
    DirectY,                      // d,Y
    DirectIndirect,               // (d)
    DirectIndexedIndirect,        // (d,X)
    DirectIndirectIndexed,        // (d),Y
    DirectIndirectLong,           // [d]
    DirectIndirectLongIndexed,    // [d],Y
    StackRelative,                // d,S
    StackRelativeIndirectIndexed, // (d,S),Y
    Relative,                     // r
    RelativeLong,                 // rl
    Stack,                        // s
    BlockMove,                    // xyc
};

// Tamaño del operando inmediato: M o X dependen del flag homónimo; Fixed8 es
// siempre 1 byte (REP, SEP). None para los modos que no son Immediate.
enum class ImmSize : std::uint8_t {
    None,
    Fixed8,
    M,
    X,
};

struct OpcodeInfo {
    Mnemonic mnemonic;
    AddrMode mode;
    std::uint8_t base_bytes;
    ImmSize imm;
};

// Indexada por opcode. base_bytes corresponde a M = 1 y X = 1.
inline constexpr std::array<OpcodeInfo, 256> kOpcodeTable{{
    /* $00 */ {Mnemonic::BRK, AddrMode::Stack, 2, ImmSize::None},
    /* $01 */ {Mnemonic::ORA, AddrMode::DirectIndexedIndirect, 2, ImmSize::None},
    /* $02 */ {Mnemonic::COP, AddrMode::Stack, 2, ImmSize::None},
    /* $03 */ {Mnemonic::ORA, AddrMode::StackRelative, 2, ImmSize::None},
    /* $04 */ {Mnemonic::TSB, AddrMode::Direct, 2, ImmSize::None},
    /* $05 */ {Mnemonic::ORA, AddrMode::Direct, 2, ImmSize::None},
    /* $06 */ {Mnemonic::ASL, AddrMode::Direct, 2, ImmSize::None},
    /* $07 */ {Mnemonic::ORA, AddrMode::DirectIndirectLong, 2, ImmSize::None},
    /* $08 */ {Mnemonic::PHP, AddrMode::Stack, 1, ImmSize::None},
    /* $09 */ {Mnemonic::ORA, AddrMode::Immediate, 2, ImmSize::M},
    /* $0A */ {Mnemonic::ASL, AddrMode::Accumulator, 1, ImmSize::None},
    /* $0B */ {Mnemonic::PHD, AddrMode::Stack, 1, ImmSize::None},
    /* $0C */ {Mnemonic::TSB, AddrMode::Absolute, 3, ImmSize::None},
    /* $0D */ {Mnemonic::ORA, AddrMode::Absolute, 3, ImmSize::None},
    /* $0E */ {Mnemonic::ASL, AddrMode::Absolute, 3, ImmSize::None},
    /* $0F */ {Mnemonic::ORA, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $10 */ {Mnemonic::BPL, AddrMode::Relative, 2, ImmSize::None},
    /* $11 */ {Mnemonic::ORA, AddrMode::DirectIndirectIndexed, 2, ImmSize::None},
    /* $12 */ {Mnemonic::ORA, AddrMode::DirectIndirect, 2, ImmSize::None},
    /* $13 */ {Mnemonic::ORA, AddrMode::StackRelativeIndirectIndexed, 2, ImmSize::None},
    /* $14 */ {Mnemonic::TRB, AddrMode::Direct, 2, ImmSize::None},
    /* $15 */ {Mnemonic::ORA, AddrMode::DirectX, 2, ImmSize::None},
    /* $16 */ {Mnemonic::ASL, AddrMode::DirectX, 2, ImmSize::None},
    /* $17 */ {Mnemonic::ORA, AddrMode::DirectIndirectLongIndexed, 2, ImmSize::None},
    /* $18 */ {Mnemonic::CLC, AddrMode::Implied, 1, ImmSize::None},
    /* $19 */ {Mnemonic::ORA, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $1A */ {Mnemonic::INC, AddrMode::Accumulator, 1, ImmSize::None},
    /* $1B */ {Mnemonic::TCS, AddrMode::Implied, 1, ImmSize::None},
    /* $1C */ {Mnemonic::TRB, AddrMode::Absolute, 3, ImmSize::None},
    /* $1D */ {Mnemonic::ORA, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $1E */ {Mnemonic::ASL, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $1F */ {Mnemonic::ORA, AddrMode::AbsoluteLongX, 4, ImmSize::None},
    /* $20 */ {Mnemonic::JSR, AddrMode::Absolute, 3, ImmSize::None},
    /* $21 */ {Mnemonic::AND, AddrMode::DirectIndexedIndirect, 2, ImmSize::None},
    /* $22 */ {Mnemonic::JSL, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $23 */ {Mnemonic::AND, AddrMode::StackRelative, 2, ImmSize::None},
    /* $24 */ {Mnemonic::BIT, AddrMode::Direct, 2, ImmSize::None},
    /* $25 */ {Mnemonic::AND, AddrMode::Direct, 2, ImmSize::None},
    /* $26 */ {Mnemonic::ROL, AddrMode::Direct, 2, ImmSize::None},
    /* $27 */ {Mnemonic::AND, AddrMode::DirectIndirectLong, 2, ImmSize::None},
    /* $28 */ {Mnemonic::PLP, AddrMode::Stack, 1, ImmSize::None},
    /* $29 */ {Mnemonic::AND, AddrMode::Immediate, 2, ImmSize::M},
    /* $2A */ {Mnemonic::ROL, AddrMode::Accumulator, 1, ImmSize::None},
    /* $2B */ {Mnemonic::PLD, AddrMode::Stack, 1, ImmSize::None},
    /* $2C */ {Mnemonic::BIT, AddrMode::Absolute, 3, ImmSize::None},
    /* $2D */ {Mnemonic::AND, AddrMode::Absolute, 3, ImmSize::None},
    /* $2E */ {Mnemonic::ROL, AddrMode::Absolute, 3, ImmSize::None},
    /* $2F */ {Mnemonic::AND, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $30 */ {Mnemonic::BMI, AddrMode::Relative, 2, ImmSize::None},
    /* $31 */ {Mnemonic::AND, AddrMode::DirectIndirectIndexed, 2, ImmSize::None},
    /* $32 */ {Mnemonic::AND, AddrMode::DirectIndirect, 2, ImmSize::None},
    /* $33 */ {Mnemonic::AND, AddrMode::StackRelativeIndirectIndexed, 2, ImmSize::None},
    /* $34 */ {Mnemonic::BIT, AddrMode::DirectX, 2, ImmSize::None},
    /* $35 */ {Mnemonic::AND, AddrMode::DirectX, 2, ImmSize::None},
    /* $36 */ {Mnemonic::ROL, AddrMode::DirectX, 2, ImmSize::None},
    /* $37 */ {Mnemonic::AND, AddrMode::DirectIndirectLongIndexed, 2, ImmSize::None},
    /* $38 */ {Mnemonic::SEC, AddrMode::Implied, 1, ImmSize::None},
    /* $39 */ {Mnemonic::AND, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $3A */ {Mnemonic::DEC, AddrMode::Accumulator, 1, ImmSize::None},
    /* $3B */ {Mnemonic::TSC, AddrMode::Implied, 1, ImmSize::None},
    /* $3C */ {Mnemonic::BIT, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $3D */ {Mnemonic::AND, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $3E */ {Mnemonic::ROL, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $3F */ {Mnemonic::AND, AddrMode::AbsoluteLongX, 4, ImmSize::None},
    /* $40 */ {Mnemonic::RTI, AddrMode::Stack, 1, ImmSize::None},
    /* $41 */ {Mnemonic::EOR, AddrMode::DirectIndexedIndirect, 2, ImmSize::None},
    /* $42 */ {Mnemonic::WDM, AddrMode::Implied, 2, ImmSize::None},
    /* $43 */ {Mnemonic::EOR, AddrMode::StackRelative, 2, ImmSize::None},
    /* $44 */ {Mnemonic::MVP, AddrMode::BlockMove, 3, ImmSize::None},
    /* $45 */ {Mnemonic::EOR, AddrMode::Direct, 2, ImmSize::None},
    /* $46 */ {Mnemonic::LSR, AddrMode::Direct, 2, ImmSize::None},
    /* $47 */ {Mnemonic::EOR, AddrMode::DirectIndirectLong, 2, ImmSize::None},
    /* $48 */ {Mnemonic::PHA, AddrMode::Stack, 1, ImmSize::None},
    /* $49 */ {Mnemonic::EOR, AddrMode::Immediate, 2, ImmSize::M},
    /* $4A */ {Mnemonic::LSR, AddrMode::Accumulator, 1, ImmSize::None},
    /* $4B */ {Mnemonic::PHK, AddrMode::Stack, 1, ImmSize::None},
    /* $4C */ {Mnemonic::JMP, AddrMode::Absolute, 3, ImmSize::None},
    /* $4D */ {Mnemonic::EOR, AddrMode::Absolute, 3, ImmSize::None},
    /* $4E */ {Mnemonic::LSR, AddrMode::Absolute, 3, ImmSize::None},
    /* $4F */ {Mnemonic::EOR, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $50 */ {Mnemonic::BVC, AddrMode::Relative, 2, ImmSize::None},
    /* $51 */ {Mnemonic::EOR, AddrMode::DirectIndirectIndexed, 2, ImmSize::None},
    /* $52 */ {Mnemonic::EOR, AddrMode::DirectIndirect, 2, ImmSize::None},
    /* $53 */ {Mnemonic::EOR, AddrMode::StackRelativeIndirectIndexed, 2, ImmSize::None},
    /* $54 */ {Mnemonic::MVN, AddrMode::BlockMove, 3, ImmSize::None},
    /* $55 */ {Mnemonic::EOR, AddrMode::DirectX, 2, ImmSize::None},
    /* $56 */ {Mnemonic::LSR, AddrMode::DirectX, 2, ImmSize::None},
    /* $57 */ {Mnemonic::EOR, AddrMode::DirectIndirectLongIndexed, 2, ImmSize::None},
    /* $58 */ {Mnemonic::CLI, AddrMode::Implied, 1, ImmSize::None},
    /* $59 */ {Mnemonic::EOR, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $5A */ {Mnemonic::PHY, AddrMode::Stack, 1, ImmSize::None},
    /* $5B */ {Mnemonic::TCD, AddrMode::Implied, 1, ImmSize::None},
    /* $5C */ {Mnemonic::JMP, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $5D */ {Mnemonic::EOR, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $5E */ {Mnemonic::LSR, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $5F */ {Mnemonic::EOR, AddrMode::AbsoluteLongX, 4, ImmSize::None},
    /* $60 */ {Mnemonic::RTS, AddrMode::Stack, 1, ImmSize::None},
    /* $61 */ {Mnemonic::ADC, AddrMode::DirectIndexedIndirect, 2, ImmSize::None},
    /* $62 */ {Mnemonic::PER, AddrMode::Stack, 3, ImmSize::None},
    /* $63 */ {Mnemonic::ADC, AddrMode::StackRelative, 2, ImmSize::None},
    /* $64 */ {Mnemonic::STZ, AddrMode::Direct, 2, ImmSize::None},
    /* $65 */ {Mnemonic::ADC, AddrMode::Direct, 2, ImmSize::None},
    /* $66 */ {Mnemonic::ROR, AddrMode::Direct, 2, ImmSize::None},
    /* $67 */ {Mnemonic::ADC, AddrMode::DirectIndirectLong, 2, ImmSize::None},
    /* $68 */ {Mnemonic::PLA, AddrMode::Stack, 1, ImmSize::None},
    /* $69 */ {Mnemonic::ADC, AddrMode::Immediate, 2, ImmSize::M},
    /* $6A */ {Mnemonic::ROR, AddrMode::Accumulator, 1, ImmSize::None},
    /* $6B */ {Mnemonic::RTL, AddrMode::Stack, 1, ImmSize::None},
    /* $6C */ {Mnemonic::JMP, AddrMode::AbsoluteIndirect, 3, ImmSize::None},
    /* $6D */ {Mnemonic::ADC, AddrMode::Absolute, 3, ImmSize::None},
    /* $6E */ {Mnemonic::ROR, AddrMode::Absolute, 3, ImmSize::None},
    /* $6F */ {Mnemonic::ADC, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $70 */ {Mnemonic::BVS, AddrMode::Relative, 2, ImmSize::None},
    /* $71 */ {Mnemonic::ADC, AddrMode::DirectIndirectIndexed, 2, ImmSize::None},
    /* $72 */ {Mnemonic::ADC, AddrMode::DirectIndirect, 2, ImmSize::None},
    /* $73 */ {Mnemonic::ADC, AddrMode::StackRelativeIndirectIndexed, 2, ImmSize::None},
    /* $74 */ {Mnemonic::STZ, AddrMode::DirectX, 2, ImmSize::None},
    /* $75 */ {Mnemonic::ADC, AddrMode::DirectX, 2, ImmSize::None},
    /* $76 */ {Mnemonic::ROR, AddrMode::DirectX, 2, ImmSize::None},
    /* $77 */ {Mnemonic::ADC, AddrMode::DirectIndirectLongIndexed, 2, ImmSize::None},
    /* $78 */ {Mnemonic::SEI, AddrMode::Implied, 1, ImmSize::None},
    /* $79 */ {Mnemonic::ADC, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $7A */ {Mnemonic::PLY, AddrMode::Stack, 1, ImmSize::None},
    /* $7B */ {Mnemonic::TDC, AddrMode::Implied, 1, ImmSize::None},
    /* $7C */ {Mnemonic::JMP, AddrMode::AbsoluteIndexedIndirect, 3, ImmSize::None},
    /* $7D */ {Mnemonic::ADC, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $7E */ {Mnemonic::ROR, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $7F */ {Mnemonic::ADC, AddrMode::AbsoluteLongX, 4, ImmSize::None},
    /* $80 */ {Mnemonic::BRA, AddrMode::Relative, 2, ImmSize::None},
    /* $81 */ {Mnemonic::STA, AddrMode::DirectIndexedIndirect, 2, ImmSize::None},
    /* $82 */ {Mnemonic::BRL, AddrMode::RelativeLong, 3, ImmSize::None},
    /* $83 */ {Mnemonic::STA, AddrMode::StackRelative, 2, ImmSize::None},
    /* $84 */ {Mnemonic::STY, AddrMode::Direct, 2, ImmSize::None},
    /* $85 */ {Mnemonic::STA, AddrMode::Direct, 2, ImmSize::None},
    /* $86 */ {Mnemonic::STX, AddrMode::Direct, 2, ImmSize::None},
    /* $87 */ {Mnemonic::STA, AddrMode::DirectIndirectLong, 2, ImmSize::None},
    /* $88 */ {Mnemonic::DEY, AddrMode::Implied, 1, ImmSize::None},
    /* $89 */ {Mnemonic::BIT, AddrMode::Immediate, 2, ImmSize::M},
    /* $8A */ {Mnemonic::TXA, AddrMode::Implied, 1, ImmSize::None},
    /* $8B */ {Mnemonic::PHB, AddrMode::Stack, 1, ImmSize::None},
    /* $8C */ {Mnemonic::STY, AddrMode::Absolute, 3, ImmSize::None},
    /* $8D */ {Mnemonic::STA, AddrMode::Absolute, 3, ImmSize::None},
    /* $8E */ {Mnemonic::STX, AddrMode::Absolute, 3, ImmSize::None},
    /* $8F */ {Mnemonic::STA, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $90 */ {Mnemonic::BCC, AddrMode::Relative, 2, ImmSize::None},
    /* $91 */ {Mnemonic::STA, AddrMode::DirectIndirectIndexed, 2, ImmSize::None},
    /* $92 */ {Mnemonic::STA, AddrMode::DirectIndirect, 2, ImmSize::None},
    /* $93 */ {Mnemonic::STA, AddrMode::StackRelativeIndirectIndexed, 2, ImmSize::None},
    /* $94 */ {Mnemonic::STY, AddrMode::DirectX, 2, ImmSize::None},
    /* $95 */ {Mnemonic::STA, AddrMode::DirectX, 2, ImmSize::None},
    /* $96 */ {Mnemonic::STX, AddrMode::DirectY, 2, ImmSize::None},
    /* $97 */ {Mnemonic::STA, AddrMode::DirectIndirectLongIndexed, 2, ImmSize::None},
    /* $98 */ {Mnemonic::TYA, AddrMode::Implied, 1, ImmSize::None},
    /* $99 */ {Mnemonic::STA, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $9A */ {Mnemonic::TXS, AddrMode::Implied, 1, ImmSize::None},
    /* $9B */ {Mnemonic::TXY, AddrMode::Implied, 1, ImmSize::None},
    /* $9C */ {Mnemonic::STZ, AddrMode::Absolute, 3, ImmSize::None},
    /* $9D */ {Mnemonic::STA, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $9E */ {Mnemonic::STZ, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $9F */ {Mnemonic::STA, AddrMode::AbsoluteLongX, 4, ImmSize::None},
    /* $A0 */ {Mnemonic::LDY, AddrMode::Immediate, 2, ImmSize::X},
    /* $A1 */ {Mnemonic::LDA, AddrMode::DirectIndexedIndirect, 2, ImmSize::None},
    /* $A2 */ {Mnemonic::LDX, AddrMode::Immediate, 2, ImmSize::X},
    /* $A3 */ {Mnemonic::LDA, AddrMode::StackRelative, 2, ImmSize::None},
    /* $A4 */ {Mnemonic::LDY, AddrMode::Direct, 2, ImmSize::None},
    /* $A5 */ {Mnemonic::LDA, AddrMode::Direct, 2, ImmSize::None},
    /* $A6 */ {Mnemonic::LDX, AddrMode::Direct, 2, ImmSize::None},
    /* $A7 */ {Mnemonic::LDA, AddrMode::DirectIndirectLong, 2, ImmSize::None},
    /* $A8 */ {Mnemonic::TAY, AddrMode::Implied, 1, ImmSize::None},
    /* $A9 */ {Mnemonic::LDA, AddrMode::Immediate, 2, ImmSize::M},
    /* $AA */ {Mnemonic::TAX, AddrMode::Implied, 1, ImmSize::None},
    /* $AB */ {Mnemonic::PLB, AddrMode::Stack, 1, ImmSize::None},
    /* $AC */ {Mnemonic::LDY, AddrMode::Absolute, 3, ImmSize::None},
    /* $AD */ {Mnemonic::LDA, AddrMode::Absolute, 3, ImmSize::None},
    /* $AE */ {Mnemonic::LDX, AddrMode::Absolute, 3, ImmSize::None},
    /* $AF */ {Mnemonic::LDA, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $B0 */ {Mnemonic::BCS, AddrMode::Relative, 2, ImmSize::None},
    /* $B1 */ {Mnemonic::LDA, AddrMode::DirectIndirectIndexed, 2, ImmSize::None},
    /* $B2 */ {Mnemonic::LDA, AddrMode::DirectIndirect, 2, ImmSize::None},
    /* $B3 */ {Mnemonic::LDA, AddrMode::StackRelativeIndirectIndexed, 2, ImmSize::None},
    /* $B4 */ {Mnemonic::LDY, AddrMode::DirectX, 2, ImmSize::None},
    /* $B5 */ {Mnemonic::LDA, AddrMode::DirectX, 2, ImmSize::None},
    /* $B6 */ {Mnemonic::LDX, AddrMode::DirectY, 2, ImmSize::None},
    /* $B7 */ {Mnemonic::LDA, AddrMode::DirectIndirectLongIndexed, 2, ImmSize::None},
    /* $B8 */ {Mnemonic::CLV, AddrMode::Implied, 1, ImmSize::None},
    /* $B9 */ {Mnemonic::LDA, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $BA */ {Mnemonic::TSX, AddrMode::Implied, 1, ImmSize::None},
    /* $BB */ {Mnemonic::TYX, AddrMode::Implied, 1, ImmSize::None},
    /* $BC */ {Mnemonic::LDY, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $BD */ {Mnemonic::LDA, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $BE */ {Mnemonic::LDX, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $BF */ {Mnemonic::LDA, AddrMode::AbsoluteLongX, 4, ImmSize::None},
    /* $C0 */ {Mnemonic::CPY, AddrMode::Immediate, 2, ImmSize::X},
    /* $C1 */ {Mnemonic::CMP, AddrMode::DirectIndexedIndirect, 2, ImmSize::None},
    /* $C2 */ {Mnemonic::REP, AddrMode::Immediate, 2, ImmSize::Fixed8},
    /* $C3 */ {Mnemonic::CMP, AddrMode::StackRelative, 2, ImmSize::None},
    /* $C4 */ {Mnemonic::CPY, AddrMode::Direct, 2, ImmSize::None},
    /* $C5 */ {Mnemonic::CMP, AddrMode::Direct, 2, ImmSize::None},
    /* $C6 */ {Mnemonic::DEC, AddrMode::Direct, 2, ImmSize::None},
    /* $C7 */ {Mnemonic::CMP, AddrMode::DirectIndirectLong, 2, ImmSize::None},
    /* $C8 */ {Mnemonic::INY, AddrMode::Implied, 1, ImmSize::None},
    /* $C9 */ {Mnemonic::CMP, AddrMode::Immediate, 2, ImmSize::M},
    /* $CA */ {Mnemonic::DEX, AddrMode::Implied, 1, ImmSize::None},
    /* $CB */ {Mnemonic::WAI, AddrMode::Implied, 1, ImmSize::None},
    /* $CC */ {Mnemonic::CPY, AddrMode::Absolute, 3, ImmSize::None},
    /* $CD */ {Mnemonic::CMP, AddrMode::Absolute, 3, ImmSize::None},
    /* $CE */ {Mnemonic::DEC, AddrMode::Absolute, 3, ImmSize::None},
    /* $CF */ {Mnemonic::CMP, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $D0 */ {Mnemonic::BNE, AddrMode::Relative, 2, ImmSize::None},
    /* $D1 */ {Mnemonic::CMP, AddrMode::DirectIndirectIndexed, 2, ImmSize::None},
    /* $D2 */ {Mnemonic::CMP, AddrMode::DirectIndirect, 2, ImmSize::None},
    /* $D3 */ {Mnemonic::CMP, AddrMode::StackRelativeIndirectIndexed, 2, ImmSize::None},
    /* $D4 */ {Mnemonic::PEI, AddrMode::Stack, 2, ImmSize::None},
    /* $D5 */ {Mnemonic::CMP, AddrMode::DirectX, 2, ImmSize::None},
    /* $D6 */ {Mnemonic::DEC, AddrMode::DirectX, 2, ImmSize::None},
    /* $D7 */ {Mnemonic::CMP, AddrMode::DirectIndirectLongIndexed, 2, ImmSize::None},
    /* $D8 */ {Mnemonic::CLD, AddrMode::Implied, 1, ImmSize::None},
    /* $D9 */ {Mnemonic::CMP, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $DA */ {Mnemonic::PHX, AddrMode::Stack, 1, ImmSize::None},
    /* $DB */ {Mnemonic::STP, AddrMode::Implied, 1, ImmSize::None},
    /* $DC */ {Mnemonic::JML, AddrMode::AbsoluteIndirect, 3, ImmSize::None},
    /* $DD */ {Mnemonic::CMP, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $DE */ {Mnemonic::DEC, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $DF */ {Mnemonic::CMP, AddrMode::AbsoluteLongX, 4, ImmSize::None},
    /* $E0 */ {Mnemonic::CPX, AddrMode::Immediate, 2, ImmSize::X},
    /* $E1 */ {Mnemonic::SBC, AddrMode::DirectIndexedIndirect, 2, ImmSize::None},
    /* $E2 */ {Mnemonic::SEP, AddrMode::Immediate, 2, ImmSize::Fixed8},
    /* $E3 */ {Mnemonic::SBC, AddrMode::StackRelative, 2, ImmSize::None},
    /* $E4 */ {Mnemonic::CPX, AddrMode::Direct, 2, ImmSize::None},
    /* $E5 */ {Mnemonic::SBC, AddrMode::Direct, 2, ImmSize::None},
    /* $E6 */ {Mnemonic::INC, AddrMode::Direct, 2, ImmSize::None},
    /* $E7 */ {Mnemonic::SBC, AddrMode::DirectIndirectLong, 2, ImmSize::None},
    /* $E8 */ {Mnemonic::INX, AddrMode::Implied, 1, ImmSize::None},
    /* $E9 */ {Mnemonic::SBC, AddrMode::Immediate, 2, ImmSize::M},
    /* $EA */ {Mnemonic::NOP, AddrMode::Implied, 1, ImmSize::None},
    /* $EB */ {Mnemonic::XBA, AddrMode::Implied, 1, ImmSize::None},
    /* $EC */ {Mnemonic::CPX, AddrMode::Absolute, 3, ImmSize::None},
    /* $ED */ {Mnemonic::SBC, AddrMode::Absolute, 3, ImmSize::None},
    /* $EE */ {Mnemonic::INC, AddrMode::Absolute, 3, ImmSize::None},
    /* $EF */ {Mnemonic::SBC, AddrMode::AbsoluteLong, 4, ImmSize::None},
    /* $F0 */ {Mnemonic::BEQ, AddrMode::Relative, 2, ImmSize::None},
    /* $F1 */ {Mnemonic::SBC, AddrMode::DirectIndirectIndexed, 2, ImmSize::None},
    /* $F2 */ {Mnemonic::SBC, AddrMode::DirectIndirect, 2, ImmSize::None},
    /* $F3 */ {Mnemonic::SBC, AddrMode::StackRelativeIndirectIndexed, 2, ImmSize::None},
    /* $F4 */ {Mnemonic::PEA, AddrMode::Stack, 3, ImmSize::None},
    /* $F5 */ {Mnemonic::SBC, AddrMode::DirectX, 2, ImmSize::None},
    /* $F6 */ {Mnemonic::INC, AddrMode::DirectX, 2, ImmSize::None},
    /* $F7 */ {Mnemonic::SBC, AddrMode::DirectIndirectLongIndexed, 2, ImmSize::None},
    /* $F8 */ {Mnemonic::SED, AddrMode::Implied, 1, ImmSize::None},
    /* $F9 */ {Mnemonic::SBC, AddrMode::AbsoluteY, 3, ImmSize::None},
    /* $FA */ {Mnemonic::PLX, AddrMode::Stack, 1, ImmSize::None},
    /* $FB */ {Mnemonic::XCE, AddrMode::Implied, 1, ImmSize::None},
    /* $FC */ {Mnemonic::JSR, AddrMode::AbsoluteIndexedIndirect, 3, ImmSize::None},
    /* $FD */ {Mnemonic::SBC, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $FE */ {Mnemonic::INC, AddrMode::AbsoluteX, 3, ImmSize::None},
    /* $FF */ {Mnemonic::SBC, AddrMode::AbsoluteLongX, 4, ImmSize::None},
}};

constexpr const char* mnemonic_name(Mnemonic m) noexcept {
    constexpr std::array<const char*, 92> kNames{{
        "ADC",
        "AND",
        "ASL",
        "BCC",
        "BCS",
        "BEQ",
        "BIT",
        "BMI",
        "BNE",
        "BPL",
        "BRA",
        "BRK",
        "BRL",
        "BVC",
        "BVS",
        "CLC",
        "CLD",
        "CLI",
        "CLV",
        "CMP",
        "COP",
        "CPX",
        "CPY",
        "DEC",
        "DEX",
        "DEY",
        "EOR",
        "INC",
        "INX",
        "INY",
        "JML",
        "JMP",
        "JSL",
        "JSR",
        "LDA",
        "LDX",
        "LDY",
        "LSR",
        "MVN",
        "MVP",
        "NOP",
        "ORA",
        "PEA",
        "PEI",
        "PER",
        "PHA",
        "PHB",
        "PHD",
        "PHK",
        "PHP",
        "PHX",
        "PHY",
        "PLA",
        "PLB",
        "PLD",
        "PLP",
        "PLX",
        "PLY",
        "REP",
        "ROL",
        "ROR",
        "RTI",
        "RTL",
        "RTS",
        "SBC",
        "SEC",
        "SED",
        "SEI",
        "SEP",
        "STA",
        "STP",
        "STX",
        "STY",
        "STZ",
        "TAX",
        "TAY",
        "TCD",
        "TCS",
        "TDC",
        "TRB",
        "TSB",
        "TSC",
        "TSX",
        "TXA",
        "TXS",
        "TXY",
        "TYA",
        "TYX",
        "WAI",
        "WDM",
        "XBA",
        "XCE",
    }};
    const auto index = static_cast<std::size_t>(m);
    return index < kNames.size() ? kNames[index] : "???";
}

// Longitud total en bytes (opcode incluido) según el estado de M y X
// (m8 / x8 = true: registro de 8 bits).
constexpr std::uint8_t instruction_length(std::uint8_t opcode, bool m8, bool x8) noexcept {
    const OpcodeInfo& info = kOpcodeTable[opcode];
    std::uint8_t length = info.base_bytes;
    if (info.imm == ImmSize::M && !m8) {
        ++length;
    }
    if (info.imm == ImmSize::X && !x8) {
        ++length;
    }
    return length;
}

} // namespace heno
